services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=example'
      - 'MYSQL_PASSWORD=suhFuq-miptap-recvo5'
      - 'MYSQL_ROOT_PASSWORD=suhFuq-miptap-recvo5'
      - 'MYSQL_USER=example'
    ports:
      - '3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 60s
      retries: 5
      start_period: 10s
    volumes:
      - db_data1:/var/lib/mysql
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass abcdefg
    volumes:
      - cache:/data
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        # waiting until the db is ready, make sure the migration will success
        condition: service_healthy

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  db_data1:
  cache: